export interface ClientRecord {
    name: string;
    domain?: string;
    /** Filename in /public/assets/webp_client/, e.g. 'Infosys.webp' */
    logo?: string;
    category: 'Government' | 'Education' | 'Corporate' | 'Startup' | 'Foundation' | 'Other';
}

export const clientsData: ClientRecord[] = [
    { name: '3rd Eye Techno Solutions', logo: '3rd Eye Techno Solutions Pvt Ltd.webp', category: 'Corporate' },
    { name: 'ACC Cement', logo: 'ACC Cement.webp', category: 'Corporate' },
    { name: 'Adani Cement', logo: 'Adani Cement.webp', category: 'Corporate' },
    { name: 'Agamya Cyber Tech', logo: 'Agamya Cyber Tech.webp', category: 'Startup' },
    { name: 'Aristo Pharmaceuticals', logo: 'Aristo Pharmaceuticals Pvt Ltd.webp', category: 'Corporate' },
    { name: 'B N Khot Group', logo: 'B N Khot Group Of Institutes.webp', category: 'Education' },
    { name: 'BNI', logo: 'BNI.webp', category: 'Other' },
    { name: 'Ballys Casino', logo: 'Ballys Casino.webp', category: 'Other' },
    { name: 'Bureau Of Indian Standards', logo: 'Bureau Of Indian Standards.webp', category: 'Government' },
    { name: 'Coromandel', logo: 'Coromandel.webp', category: 'Corporate' },
    { name: 'Corteva Agriscience', logo: 'Corteva Agriscience.webp', category: 'Corporate' },
    { name: 'Deshpande Foundation', logo: 'Deshpande Foundation.webp', category: 'Foundation' },
    { name: 'Deshpande Startups', logo: 'Deshpande Startups.webp', category: 'Startup' },
    { name: 'District Health Assn', logo: 'District Health & Family Welfare Association.webp', category: 'Government' },
    { name: 'Global Public School', logo: 'Global Public School & PU College Karatagi.webp', category: 'Education' },
    { name: 'Govt of Karnataka', logo: 'Government Of Karnataka.webp', category: 'Government' },
    { name: 'Gram Vikas Society', logo: 'Gram Vikas Society.webp', category: 'Foundation' },
    { name: 'High5 Studios', logo: 'High5 Studios Pvt Ltd.webp', category: 'Startup' },
    { name: 'Hodek Vibrations', logo: 'Hodek Vibrations Technologies Pvt Ltd.webp', category: 'Corporate' },
    { name: 'IIIT Dharwad', logo: 'IIIT Dharwad.webp', category: 'Education' },
    { name: 'IIT Dharwad', logo: 'IIT Dharwad.webp', category: 'Education' },
    { name: 'Infosys', logo: 'Infosys.webp', category: 'Corporate' },
    { name: 'Inner Wheel Club', logo: 'Inner Wheel Clun Hubballi.webp', category: 'Other' },
    { name: 'Inorbit Malls', logo: 'Inorbit Malls India Pvt Ltd.webp', category: 'Corporate' },
    { name: 'Jockey', logo: 'Jockey.webp', category: 'Corporate' },
    { name: 'KIMS Hubballi', logo: 'KIMS Hubballi.webp', category: 'Education' },
    { name: 'KLE BBA Hubli', logo: 'KLE BBA Hubli.webp', category: 'Education' },
    { name: 'KLE Society', logo: 'KLE Society.webp', category: 'Education' },
    { name: 'Spices Board', logo: 'Karnataka State Spices Deveopment Board.webp', category: 'Government' },
    { name: 'MYOP Perfume', logo: 'MYOP- Make Your Own Perfume.webp', category: 'Other' },
    { name: 'MEAI', logo: 'Media & Entertainment Association Of India.webp', category: 'Other' },
    { name: 'Metabolic Health', logo: 'Metabolic Health India.webp', category: 'Other' },
    { name: 'Miniso', logo: 'Miniso.webp', category: 'Corporate' },
    { name: 'Nagshanti Group', logo: 'Nagshanti Group Of Companies.webp', category: 'Corporate' },
    { name: 'Paradeep Phosphates', logo: 'Paradeep Phosphates.webp', category: 'Corporate' },
    { name: 'Patanjali', logo: 'Patanjali.webp', category: 'Corporate' },
    { name: 'RCF Ltd', logo: 'Rashrtiya Chemicals & Fertilizers Ltd.webp', category: 'Government' },
    { name: 'Rotary Club', logo: 'Rotary Club Of Hubli.webp', category: 'Other' },
    { name: 'Samyukta Karnataka', logo: 'Samyukta Karnataka.webp', category: 'Other' },
    { name: 'Selco Foundation', logo: 'Selco Foundation.webp', category: 'Foundation' },
    { name: 'Shri Durga Developers', logo: 'Shri Durga Deveopers & Promoters.webp', category: 'Corporate' },
    { name: 'Sadashivanand School', logo: 'Shri Jagadguru Sadashivanand English Medium School.webp', category: 'Education' },
    { name: 'Shri Rajeshwari Properties', logo: 'Shri Rajeshwari Properties.webp', category: 'Corporate' },
    { name: 'Shriya Properties', logo: 'Shriya Properties.webp', category: 'Corporate' },
    { name: 'Sulthan Diamonds', logo: 'Sulthan Fiamonds & Gold.webp', category: 'Corporate' },
    { name: 'TIE Hubli', logo: 'TIE Hubli.webp', category: 'Startup' },
    { name: 'TalenTree India', logo: 'TalenTree India.webp', category: 'Other' },
    { name: 'Tejas Institutions', logo: 'Tejas International Educational Institutions.webp', category: 'Education' },
    { name: 'Trust Grow Fertilizers', logo: 'Trust Grow Fertilizers.webp', category: 'Corporate' },
    { name: 'Uni Abex Alloys', logo: 'Uni Abex Alloys Products Limited.webp', category: 'Corporate' },
    { name: 'VRL', logo: 'VRL.webp', category: 'Corporate' },
    { name: 'Vijayavani', logo: 'Vijayavani.webp', category: 'Other' },
    { name: 'Volvo', logo: 'Volvo.webp', category: 'Corporate' },
    { name: 'Zilla Panchayat Dharwad', logo: 'Zilla Panchayat Dharwad.webp', category: 'Government' },
    { name: 'Zuari FarmHub', logo: 'Zuari FarmHub.webp', category: 'Other' },
];
