export interface ClientRecord {
    name: string;
    domain?: string;
    /** Filename in /public/assets/clientLogo/, e.g. 'volvo.png' or 'infosys.svg' */
    logo?: string;
    category: 'Government' | 'Education' | 'Corporate' | 'Startup' | 'Foundation' | 'Other';
}

export const clientsData: ClientRecord[] = [
    { name: 'Deshpande Foundation', domain: 'deshpandefoundationindia.org', logo: 'Deshpande-foundation-logo.png', category: 'Foundation' },
    { name: 'Deshpande Startups', domain: 'deshpandestartups.org', category: 'Startup' },
    { name: 'KLE Society', domain: 'klesociety.org', logo: 'kle logo.png', category: 'Education' },
    { name: 'Volvo', domain: 'volvo.com', category: 'Corporate' },
    { name: 'Infosys', domain: 'infosys.com', logo: 'infosys-logo-png.png', category: 'Corporate' },
    { name: 'Durga Developers', domain: 'durgadevelopers.in', logo: 'durga developers.png', category: 'Corporate' },
    { name: 'TiE Hubli', domain: 'hubli.tie.org', logo: 'tiecon.png', category: 'Startup' },
    { name: 'VRL', domain: 'vrlgroup.in', logo: 'VRLLOGO.svg', category: 'Corporate' },
    { name: 'Vijay Vani', domain: 'vijayavani.net', logo: 'vijayvani.webp', category: 'Corporate' },
    { name: 'Patanjali', domain: 'patanjaliayurved.net', category: 'Corporate' },
    { name: 'KLE BBA', domain: 'klebba.in', logo: 'kle logo.png', category: 'Education' },
    { name: 'Selco Foundation', domain: 'selcofoundation.org', logo: 'SELCO_India_logo.svg.png', category: 'Foundation' },
    { name: 'Bureau of Indian Standards', domain: 'bis.gov.in', logo: 'b i s.png', category: 'Government' },
    { name: 'Rashtriya Chemical Fertilizers', domain: 'rcfltd.com', logo: 'rashtriya chemical fertiliers.png', category: 'Government' },
    { name: 'Media & Entertainment Association of India', domain: 'meai.in', category: 'Other' },
    { name: 'Syngenta', domain: 'syngenta.co.in', logo: 'sygnets.webp', category: 'Corporate' },
    { name: 'Nagshanti Groups', domain: 'nagshanti.com', logo: 'nagshanti group.png', category: 'Corporate' },
    { name: 'District Health & Family Welfare', domain: 'karunadu.karnataka.gov.in/hfw', logo: 'govt of karnataka.png', category: 'Government' },
    { name: 'Sanyukta Karnataka', domain: 'samyukthakarnataka.com', logo: 'samyukta karnataka.png', category: 'Corporate' },
    { name: 'Roka Shikshana Trust', category: 'Education' },
    { name: 'Costena Agri Science', domain: 'costenaagriscience.com', logo: 'corteva.png', category: 'Corporate' },
    { name: 'Spices Board India', domain: 'indianspices.com', category: 'Government' },
    { name: 'IIIT Dharwad', domain: 'iiitdwd.ac.in', logo: 'iiit dharwad.webp', category: 'Education' },
    { name: 'ZWii Farmhub', domain: 'farmhub.in', logo: 'zuri farmhub.png', category: 'Startup' },
    { name: 'BN Khata International School', category: 'Education' },
    { name: 'Head Held High Foundation', domain: 'headheldhigh.org', logo: 'head held high.png', category: 'Foundation' },
    { name: 'Grama Vikas Society', logo: 'gram vikas.png', category: 'Foundation' },
    { name: 'Talentry Consulting Pvt Ltd', domain: 'talentry.in', category: 'Corporate' },
    { name: 'Leading Lights People Services', domain: 'leadinglightspeopleservices.com', category: 'Corporate' },
    { name: 'Avisto Pharmaceuticals', domain: 'avistopharma.com', logo: 'aristo pharma.png', category: 'Corporate' },
    { name: 'Hodek Vibration Technology', domain: 'hodek.com', logo: 'hodek.png', category: 'Corporate' },
    { name: 'Sultan Diamonds & Gold', domain: 'sultangroup.in', logo: 'sultan gold.png', category: 'Corporate' },
    { name: 'Hi-Fi Studios', domain: 'hifistudio.in', logo: 'hi fi studios.png', category: 'Corporate' },
    { name: 'KIMS Hubli', domain: 'kimshubballi.org', category: 'Government' },
    { name: 'Dept of Handloom & Textile', logo: 'govt of karnataka.png', category: 'Government' },
    { name: 'Zilla Panchayat Dharwad', domain: 'zpdharwad.kar.nic.in', logo: 'dharwad zilla panchayat.png', category: 'Government' },
    { name: '3rd Eye Techno Solutions', domain: '3rdeyetechno.com', logo: '3rd eye techno sols.png', category: 'Corporate' },
    { name: 'Trust Grow Fertilizers', logo: 'trust grow fertilizers.png', category: 'Corporate' },
    { name: 'Talentry Consulting Dharwad', domain: 'talentry.in', category: 'Corporate' },
    { name: 'Inorbit Malls Hubli', domain: 'inorbit.in', logo: 'inorbit.png', category: 'Corporate' },
    { name: 'Make Your Own Perfume', domain: 'myop.in', logo: 'make your own perfume.png', category: 'Corporate' },
    { name: 'IIT Dharwad', domain: 'iitdh.ac.in', logo: 'iit dharwad.png', category: 'Education' },
    { name: 'Uni Abex Alloy Products', domain: 'uniabex.com', logo: 'uni abex.png', category: 'Corporate' },
    { name: 'Shreeya Property', domain: 'shreeyaproperties.com', category: 'Corporate' },
    { name: 'Metabolic Health India', logo: 'metabolic health india.png', category: 'Other' },
    { name: 'Tejas International School', domain: 'tejasinternationalschool.com', logo: 'tejas international school.png', category: 'Education' },
    { name: 'SK Silks & Sarees', logo: 'eskay.png', category: 'Corporate' },
    { name: 'Ganesh Hotel (Crave)', logo: 'crave.png', category: 'Corporate' },
    { name: 'Arrow Clothing', domain: 'arrowlife.com', logo: 'arrow clothing.png', category: 'Corporate' },
    { name: 'Bally\'s Casino', domain: 'ballys.com', logo: 'bally casino.png', category: 'Corporate' },
    { name: 'Paradeep Phosphates', domain: 'paradeepphosphates.com', logo: 'paradeep_phosphates.png', category: 'Corporate' },
    { name: 'Karanji International School', category: 'Education' },
    { name: 'Dharwad International School', category: 'Education' },
    { name: 'Naan 2.0 Startup Karnataka', logo: 'nain startup.png', category: 'Startup' },
    { name: 'Agamya Cyberstek', domain: 'agamyacyberstek.com', logo: 'agamya cybertech.png', category: 'Corporate' },
    { name: 'Rajeshwari Properties', logo: 'shree rajeshwari properties.png', category: 'Corporate' },
    { name: 'SDM Dental', domain: 'sdmdentalcollege.edu', logo: 'sdm dental.png', category: 'Education' },
    { name: 'Annigeri School Gadag', category: 'Education' },
    { name: 'Inner Wheel Club', domain: 'innerwheelindia.org', category: 'Other' },
    { name: 'Business Network International', domain: 'bni.com', logo: 'bni.webp', category: 'Corporate' },
    { name: 'Coromandel International', domain: 'coromandel.biz', logo: 'coromandal.png', category: 'Corporate' },
    { name: 'Rotary Club', domain: 'rotary.org', logo: 'rotary.webp', category: 'Other' },
    { name: 'Jockey', domain: 'jockey.in', logo: 'jockey.png', category: 'Corporate' },
    { name: 'Miniso', domain: 'miniso.com', logo: 'minisow.webp', category: 'Corporate' },
    { name: 'Ambuja Cements', domain: 'ambujacement.com', logo: 'adani.webp', category: 'Corporate' },
    { name: 'ACC Cements', domain: 'acclimited.com', logo: 'acc.webp', category: 'Corporate' },
    { name: 'Global Public School Karatagi', category: 'Education' },
];

