export interface ClientRecord {
    name: string;
    domain?: string;
    /** Filename in /public/assets/clientLogo/, e.g. 'volvo.png' or 'infosys.svg' */
    logo?: string;
}

export const clientsData: ClientRecord[] = [
    { name: 'Deshpande Foundation', domain: 'deshpandefoundationindia.org', logo: 'Deshpande-foundation-logo.png' },
    { name: 'Deshpande Startups', domain: 'deshpandestartups.org' }, // no exact match, skip
    { name: 'KLE Society', domain: 'klesociety.org', logo: 'kle logo.png' },
    { name: 'Volvo', domain: 'volvo.com' },
    { name: 'Infosys', domain: 'infosys.com', logo: 'infosys-logo-png.png' },
    { name: 'Durga Developers', domain: 'durgadevelopers.in', logo: 'durga developers.png' },
    { name: 'TiE Hubli', domain: 'hubli.tie.org', logo: 'tiecon.png' },
    { name: 'VRL', domain: 'vrlgroup.in', logo: 'VRLLOGO.svg' },
    { name: 'Vijay Vani', domain: 'vijayavani.net', logo: 'vijayvani.webp' },
    { name: 'Patanjali', domain: 'patanjaliayurved.net' },
    { name: 'KLE BBA', domain: 'klebba.in', logo: 'kle logo.png' },
    { name: 'Selco Foundation', domain: 'selcofoundation.org', logo: 'SELCO_India_logo.svg.png' },
    { name: 'Bureau of Indian Standards', domain: 'bis.gov.in', logo: 'b i s.png' },
    { name: 'Rashtriya Chemical Fertilizers', domain: 'rcfltd.com', logo: 'rashtriya chemical fertiliers.png' },
    { name: 'Media & Entertainment Association of India', domain: 'meai.in' },
    { name: 'Syngenta', domain: 'syngenta.co.in', logo: 'sygnets.webp' },
    { name: 'Nagshanti Groups', domain: 'nagshanti.com', logo: 'nagshanti group.png' },
    { name: 'District Health & Family Welfare', domain: 'karunadu.karnataka.gov.in/hfw', logo: 'govt of karnataka.png' },
    { name: 'Sanyukta Karnataka', domain: 'samyukthakarnataka.com', logo: 'samyukta karnataka.png' },
    { name: 'Roka Shikshana Trust' },
    { name: 'Costena Agri Science', domain: 'costenaagriscience.com', logo: 'corteva.png' },
    { name: 'Spices Board India', domain: 'indianspices.com' },
    { name: 'IIIT Dharwad', domain: 'iiitdwd.ac.in', logo: 'iiit dharwad.webp' },
    { name: 'ZWii Farmhub', domain: 'farmhub.in', logo: 'zuri farmhub.png' },
    { name: 'BN Khata International School' },
    { name: 'Head Held High Foundation', domain: 'headheldhigh.org', logo: 'head held high.png' },
    { name: 'Grama Vikas Society', logo: 'gram vikas.png' },
    { name: 'Talentry Consulting Pvt Ltd', domain: 'talentry.in' },
    { name: 'Leading Lights People Services', domain: 'leadinglightspeopleservices.com' },
    { name: 'Avisto Pharmaceuticals', domain: 'avistopharma.com', logo: 'aristo pharma.png' },
    { name: 'Hodek Vibration Technology', domain: 'hodek.com', logo: 'hodek.png' },
    { name: 'Sultan Diamonds & Gold', domain: 'sultangroup.in', logo: 'sultan gold.png' },
    { name: 'Hi-Fi Studios', domain: 'hifistudio.in', logo: 'hi fi studios.png' },
    { name: 'KIMS Hubli', domain: 'kimshubballi.org' },
    { name: 'Dept of Handloom & Textile', logo: 'govt of karnataka.png' },
    { name: 'Zilla Panchayat Dharwad', domain: 'zpdharwad.kar.nic.in', logo: 'dharwad zilla panchayat.png' },
    { name: '3rd Eye Techno Solutions', domain: '3rdeyetechno.com', logo: '3rd eye techno sols.png' },
    { name: 'Trust Grow Fertilizers', logo: 'trust grow fertilizers.png' },
    { name: 'Talentry Consulting Dharwad', domain: 'talentry.in' },
    { name: 'Inorbit Malls Hubli', domain: 'inorbit.in', logo: 'inorbit.png' },
    { name: 'Make Your Own Perfume', domain: 'myop.in', logo: 'make your own perfume.png' },
    { name: 'IIT Dharwad', domain: 'iitdh.ac.in', logo: 'iit dharwad.png' },
    { name: 'Uni Abex Alloy Products', domain: 'uniabex.com', logo: 'uni abex.png' },
    { name: 'Shreeya Property', domain: 'shreeyaproperties.com' },
    { name: 'Metabolic Health India', logo: 'metabolic health india.png' },
    { name: 'Tejas International School', domain: 'tejasinternationalschool.com', logo: 'tejas international school.png' },
    { name: 'SK Silks & Sarees', logo: 'eskay.png' },
    { name: 'Ganesh Hotel (Crave)', logo: 'crave.png' },
    { name: 'Arrow Clothing', domain: 'arrowlife.com', logo: 'arrow clothing.png' },
    { name: 'Bally\'s Casino', domain: 'ballys.com', logo: 'bally casino.png' },
    { name: 'Paradeep Phosphates', domain: 'paradeepphosphates.com' },
    { name: 'Karanji International School' },
    { name: 'Dharwad International School' },
    { name: 'Naan 2.0 Startup Karnataka', logo: 'nain startup.png' },
    { name: 'Agamya Cyberstek', domain: 'agamyacyberstek.com', logo: 'agamya cybertech.png' },
    { name: 'Rajeshwari Properties', logo: 'shree rajeshwari properties.png' },
    { name: 'SDM Dental', domain: 'sdmdentalcollege.edu', logo: 'sdm dental.png' },
    { name: 'Annigeri School Gadag' },
    { name: 'Inner Wheel Club', domain: 'innerwheelindia.org' },
    { name: 'Business Network International', domain: 'bni.com', logo: 'bni.webp' },
    { name: 'Coromandel International', domain: 'coromandel.biz', logo: 'coromandal.png' },
    { name: 'Rotary Club', domain: 'rotary.org', logo: 'rotary.webp' },
    { name: 'Jockey', domain: 'jockey.in', logo: 'jockey.png' },
    { name: 'Miniso', domain: 'miniso.com', logo: 'minisow.webp' },
    { name: 'Ambuja Cements', domain: 'ambujacement.com', logo: 'adani.webp' },
    { name: 'ACC Cements', domain: 'acclimited.com', logo: 'acc.webp' },
    { name: 'Global Public School Karatagi' },
];
