export const transparentBrands = [
{ name: "3rd Eye Techno Solutions Pvt Ltd", logo: "3rd Eye Techno Solutions Pvt Ltd.png" },
{ name: "ACC Cement", logo: "ACC Cement.png" },
{ name: "Adani Cement", logo: "Adani Cement.png" },
{ name: "Agamya Cyber Tech", logo: "Agamya Cyber Tech.png" },
{ name: "Aristo Pharmaceuticals Pvt Ltd", logo: "Aristo Pharmaceuticals Pvt Ltd.png" },
{ name: "B N Khot Group Of Institutes", logo: "B N Khot Group Of Institutes.png" },
{ name: "BNI", logo: "BNI.png" },
{ name: "Bureau Of Indian Standards", logo: "Bureau Of Indian Standards.png" },
{ name: "Coromandel", logo: "Coromandel.png" },
{ name: "Deshpande Foundation", logo: "Deshpande Foundation.png" },
{ name: "Deshpande Startups", logo: "Deshpande Startups.png" },
{ name: "District Health & Family Welfare Association", logo: "District Health & Family Welfare Association.png" },
{ name: "Global Public School & PU College Karatagi", logo: "Global Public School & PU College Karatagi.png" },
{ name: "Government Of Karnataka", logo: "Government Of Karnataka.png" },
{ name: "Gram Vikas Society", logo: "Gram Vikas Society.png" },
{ name: "Hodek Vibrations Technologies Pvt Ltd", logo: "Hodek Vibrations Technologies Pvt Ltd.png" },
{ name: "IIIT Dharwad", logo: "IIIT Dharwad.png" },
{ name: "IIT Dharwad", logo: "IIT Dharwad.png" },
{ name: "Infosys", logo: "Infosys.png" },
{ name: "Inner Wheel Clun Hubballi", logo: "Inner Wheel Clun Hubballi.png" },
{ name: "Inorbit Malls India Pvt Ltd", logo: "Inorbit Malls India Pvt Ltd.png" },
{ name: "Jockey", logo: "Jockey.png" },
{ name: "Karnataka State Spices Deveopment Board", logo: "Karnataka State Spices Deveopment Board.png" },
{ name: "KIMS Hubballi", logo: "KIMS Hubballi.png" },
{ name: "KLE BBA Hubli", logo: "KLE BBA Hubli.png" },
{ name: "KLE Society", logo: "KLE Society.png" },
{ name: "Media & Entertainment Association Of India", logo: "Media & Entertainment Association Of India.png" },
{ name: "Metabolic Health India", logo: "Metabolic Health India.png" },
{ name: "Miniso", logo: "Miniso.png" },
{ name: "MYOP- Make Your Own Perfume", logo: "MYOP- Make Your Own Perfume.png" },
{ name: "Nagshanti Group Of Companies", logo: "Nagshanti Group Of Companies.png" },
{ name: "Paradeep Phosphates", logo: "Paradeep Phosphates.png" },
{ name: "Patanjali", logo: "Patanjali.png" },
{ name: "Rashrtiya Chemicals & Fertilizers Ltd", logo: "Rashrtiya Chemicals & Fertilizers Ltd.png" },
{ name: "Rotary Club Of Hubli", logo: "Rotary Club Of Hubli.png" },
{ name: "Samyukta Karnataka", logo: "Samyukta Karnataka.png" },
{ name: "Selco Foundation", logo: "Selco Foundation.png" },
{ name: "Shri Durga Deveopers & Promoters", logo: "Shri Durga Deveopers & Promoters.png" },
{ name: "Shri Jagadguru Sadashivanand English Medium School", logo: "Shri Jagadguru Sadashivanand English Medium School.png" },
{ name: "Shri Rajeshwari Properties", logo: "Shri Rajeshwari Properties.png" },
{ name: "Shriya Properties", logo: "Shriya Properties.png" },
{ name: "Sulthan Fiamonds & Gold", logo: "Sulthan Fiamonds & Gold.png" },
{ name: "TalenTree India", logo: "TalenTree India.png" },
{ name: "Tejas International Educational Institutions", logo: "Tejas International Educational Institutions.png" },
{ name: "TIE Hubli", logo: "TIE Hubli.png" },
{ name: "Trust Grow Fertilizers", logo: "Trust Grow Fertilizers.png" },
{ name: "Uni Abex Alloys Products Limited", logo: "Uni Abex Alloys Products Limited.png" },
{ name: "Vijayavani", logo: "Vijayavani.png" },
{ name: "Volvo", logo: "Volvo.png" },
{ name: "VRL", logo: "VRL.png" },
{ name: "Zilla Panchayat Dharwad", logo: "Zilla Panchayat Dharwad.png" },
{ name: "Zuari FarmHub", logo: "Zuari FarmHub.png" }
];
